### ISSUE TITLE
Please fix installinstallmacos.py to sort by Post Date

### ISSUE THREAD

**Issue by danielbair** [munki/macadmin-scripts#101]
Please fix installinstallmacos.py to sort by Post Date. It is very difficult to pick the latest version with the current list order.

**Comment by grahamgilbert** [comment]
This sounds like an easy fix for an interested party. Personally, this has never bothered me as the list is incredibly short.

**Comment by gregneagle** [comment]
No plans to do this myself. Would review a PR.
