### ISSUE TITLE
Feature request: add option for installinstallmacos.py to simply list builds without need for root (or MacOS python)

### ISSUE THREAD

**Issue by anbroid** [munki/macadmin-scripts#102]
It would be useful to add an option to just list what's available (without prompting the user to download), and in that case remove the requirement for root/sudo. It would be cool to also avoid importing xattr in this case, so the tool isn't tied to the particular MacOS python. Even better (if possible), make this script able to run on other OS like Linux for the use case of just listing what builds apple has available! (or perhaps create separate list-only host-agnostic script).

**Comment by gregneagle** [comment]
Feel free to fork it to do any/all of these things. I don't plan to do anything more with this except necessary fixes to keep it running as long as possible. Graham Pugh has a fork with a different set of features, and I've heard of other similar tools, some of which run just fine on Linux.
