### ISSUE TITLE
installinstallmacos.py: Broken on Monterey?

### ISSUE THREAD

**Issue by welby12** [munki/macadmin-scripts#103]
The `installinstallmacos.py` script, which worked for me 2 days ago on Big Sur, appears to be broken after upgrading to macOS Monterey. 

I downloaded a fresh copy of the repo, and still same message. 

Can anyone else confirm? By the way, I went all the way up to the latest 12.3 developer beta, 21E5196i
<img width="882" alt="Screen Shot 2022-01-31 at 6 21 10 PM" src="https://user-images.githubusercontent.com/13987200/151904136-7d39fbe7-0bec-43c7-9dac-d0af225ccf7e.png">

**Comment by gregneagle** [comment]
macOS 12.3 removes Python, so you’ll need to install your own Python.

**Comment by welby12** [comment]
Good catch on macOS 12.3. Unfortunately the fix doesn't seem to be as simple as installing/using Python 3 from Homebrew. Not sure if I can fix this part, as not a Python code
<img width="1178" alt="Screen Shot 2022-02-01 at 1 52 13 PM" src="https://user-images.githubusercontent.com/13987200/152057734-63643aec-50b5-4881-b0c3-5695c7913e46.png">
r

**Comment by grahampugh** [comment]
`python3 -m pip install xattr` should do it.

**Comment by gregneagle** [comment]
You'd need to use pip to install xattr as well.

**Comment by welby12** [comment]
All very helpful, thanks guy! The final result is that I'm too cutting edge new for this script apparently.
<img width="1178" alt="Screen Shot 2022-02-01 at 1 55 59 PM" src="https://user-images.githubusercontent.com/13987200/152058203-05381465-ea6a-4f0a-93a1-d768fb76f23b.png">

**Comment by gregneagle** [comment]
Do you actually have the latest version of the script?

**Comment by welby12** [comment]
Consider the issue resolved! Sorry for such basic questions about Python (and forgetting to update the repo) 

Love this script, the DMGs are my favorite way to store macOS installers! 🙏

**Comment by songxing10000** [comment]
python3 -m pip install xattr
sudo python3 installinstallmacos.py

it work
