### ISSUE TITLE
error big sur

### ISSUE THREAD

**Issue by MechanicAri** [munki/macadmin-scripts#107]
curl: (22) The requested URL returned error: 416
Making empty sparseimage...
installer: Package name is macOS Big Sur
installer: Installing at base path /private/tmp/dmg.t9A4vb
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “InstallAssistant.pkg”.)
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/05/24/002-23589-A_ZQQIIUQAXQ/zn8n836sojdlmlvqdu7n2k4gj8roqmcysu/002-23589.English.dist', u'-target', '/private/tmp/dmg.t9A4vb']' returned non-zero exit status 1
Product installation failed.

**Comment by gregneagle** [comment]
Was successful today creating both 12.3 and 11.6.5 installer disk images. Have you read the documentation and followed its recommendations, especially around avoiding Privacy Protected directories as "working space"?

**Comment by gregneagle** [comment]
@grahampugh Actually 416 doesn't mean the download failed. It's also the code you get when you attempt to resume an already complete download.

**Comment by MechanicAri** [comment]
I did it 1 time and after i deleted the download by accident and i tried it again and it gave me this error

**Comment by MechanicAri** [comment]
oh I switched directorys and it worked because i was on mac catalina thank you
