### ISSUE TITLE
this tool requires xattr but i already have xattr

### ISSUE THREAD

**Issue by MechanicAri** [munki/macadmin-scripts#110]
hi I was trying to get a file from installinstallmacos.py but it gave me:

This tool requires the Python xattr module. Perhaps run `pip install xattr` to install it.

so i ran pip3 install xattr and it installed it but it still says:

This tool requires the Python xattr module. Perhaps run `pip install xattr` to install it.

can u help

**Comment by MechanicAri** [comment]
nevermind i reinstalled pip and it worked

**Comment by shapowhelan** [comment]
@LeeBinder  
This can happen when you install xattr as a normal user and you run the python script as a sudo user and as such xattr has not been installed for sudo.  

The following can be used fix this:
If you start 1 folder level above the macadmin-scipts folder.
create and activate a virtual env using venv
```
python -m venv macadmin-scripts
source macadmin-scripts/bin/activate
```
you should see this (macadmin-scripts) at the start of the command prompt when the virtual env is activated.
Now install xattr using pip
```
pip install --upgrade pip
pip install xattr
```
with venv still active, you can run sudo commands on the python files that require it, and they'll be able to use xattr.
```
cd macadmin-scripts/
sudo ./installinstallmacos.py 
```

**Comment by LeeBinder** [comment]
awesome, thanks @shapowhelan for sharing these instructions. I'll report back in a couple of days once I'm back on that Mac if I was successful by means of your manual 👍

**Comment by LeeBinder** [comment]
You ROCK, @shapowhelan - running in venv indeed works to navigate around xattrb not found - many taps on your shoulder 👍 Additionally only had to specify python3 here in this macOS install, that's all.

I've created a little one-click do-it-all .command script which creates the macadmin-scripts folder, downloads installinstallmacos.py from here into it then runs it in venv :) -> [run installinstallmacos py xattrb-friendly in venv.zip](https://github.com/munki/macadmin-scripts/files/13708839/run.installinstallmacos.py.xattrb-friendly.in.venv.zip)
