### ISSUE TITLE
Where does installinstallmacos.py put its cache files?

### ISSUE THREAD

**Issue by abacefbeca** [munki/macadmin-scripts#120]
I'm having trouble building an installer on a virtual machine, something to do with a disk error I think, but I've already downloaded the needed files. I was hoping to transfer the cached files over to another macOS computer and try building the installer there and skip redownloading 11GB. I guess I'm a macOS noob. I can't figure out where the cache files for the Python script are stored. Where can I find them? Or, is copything the cache files over to another computer not going to work like I'm hoping? I see an option in the documentation to ignore the cache but I see no info about where the cache is located.

**Comment by gregneagle** [comment]
Everything is stored in the same directory as ./installinstallmacos.py
