### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Tb3986** [munki/macadmin-scripts#122]
![Untitled](https://github.com/munki/macadmin-scripts/assets/45364981/8d293f64-d9be-4f55-ab60-223fc3dd0279)

Hello,
i have a stupid error.
When i launch the command: sudo ./installinstallmacos.py i get this: No such file or directory

I already installed python 3.10.
Any tips?
OS: Monterey  v12.7

Thanks

**Comment by gregneagle** [comment]
Did you install Python?
