### ISSUE TITLE
add macOS Sequoia search catalog

### ISSUE THREAD

**Issue by islamadel** [munki/macadmin-scripts#127]
https://swscan.apple.com/content/catalogs/others/index-15seed-15-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz

**Comment by gregneagle** [comment]
Shouldn't it be 
https://swscan.apple.com/content/catalogs/others/index-15-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
?

**Comment by islamadel** [comment]
true

**Comment by gregneagle** [comment]
Added here: https://github.com/munki/macadmin-scripts/commit/77e507e4351bd35db771706c4f3d6955b6bce968.
