### ISSUE TITLE
Sparse image is empty after Terminal error (MacBook Pro 2018 T2 w/Biometrics)

### ISSUE THREAD

**Issue by robertspeers62** [munki/macadmin-scripts#14]
Trying to download 10.13.6, Build 17G66 (this is the only High Sierra build listed) and I receive this error upon creating the sparse image:

_installer: Error - ERROR_2062F74259
Command '['/usr/sbin/installer', '-pkg', './content/downloads/12/40/091-95155/piv8296jbzadg8qb5m3gatbllz60d2flsw/091-95155.English.dist', '-target', '/private/tmp/dmg.mmQdwz']' returned non-zero exit status 1
Product installation failed._0

When I checked my home folder, it did create a sparseimage but it is empty when mounting it. I checked the install.log and attached the file.
[install.log](https://github.com/munki/macadmin-scripts/files/2894731/install.log)

**Comment by gregneagle** [comment]
You are trying to download and build an installer for a build of macOS that is incompatible with your current hardware. The (July) 2018 MBP requires 10.13.6 Build 17G2208 or 10.14.

Before you object with "that build isn't available in Apple's catalogs any longer": yep. That's not in my or your control. Best talk to Apple about that.

https://github.com/munki/macadmin-scripts#installinstallmacospy
```
If you attempt to install an incompatible version of macOS, you'll see an error similar to the following:

Making empty sparseimage...
installer: Error - ERROR_B14B14D9B7
Command '['/usr/sbin/installer', '-pkg', './content/downloads/07/20/091-95774/awldiototubemmsbocipx0ic9lj2kcu0pt/091-95774.English.dist', '-target', '/private/tmp/dmg.Hf0PHy']' returned non-zero exit status 1
Product installation failed.

Use a compatible Mac or select a different build compatible with your current hardware and try again. You may also have success running the script in a VM; the InstallationCheck script in versions of the macOS installer to date skips the checks (and returns success) when run on a VM.```
