### ISSUE TITLE
Wrong build number at the end

### ISSUE THREAD

**Issue by hrytskivr** [munki/macadmin-scripts#15]
I've used this script to download 17G2208, mounted the dmg, copied over to /Applications but then when I re-check the build number I get this:
Code:
$ cat /Applications/Install\ macOS\ High\ Sierra.app/Contents/Info.plist | grep -A 1 DTSDKBuild
    <key>DTSDKBuild</key>
    <string>17G2205</string>

So it seems to be 2205 instead of 2208 after all, what could be the reason?

**Comment by gregneagle** [comment]
There is zero guarantee that the build number of the Install macOS application matches the build number of the OS it installs. Instead you should be looking at the ProductBuildVersion inside /System/Library/CoreServices/SystemVersion.plist in the mounted BaseSystem.dmg.

```
hdiutil attach Install\ macOS\ High| Sierra.app/Contents/SharedSupport/BaseSystem.dmg
cat "/Volumes/OS X Base System/System/Library/CoreServices/SystemVersion.plist"
```
