### ISSUE TITLE
No options for Mojave beta

### ISSUE THREAD

**Issue by stevemoser** [munki/macadmin-scripts#17]
Currently I see these options output from the installinstallmacos script:

`
 1    041-47723    10.14.4  18E2034  2019-03-25  macOS Mojave
 2    091-95155    10.13.6    17G66  2019-01-08  macOS High Sierra
 3    041-49229    10.14.4   18E226  2019-03-25  macOS Mojave
`

I'm looking for 10.14.5 beta. Thoughts?

**Comment by gregneagle** [comment]
You'd have to point the tool at an Apple sucatalog that contains the 10.14.5 beta full installer, if such a thing exists. Have you checked the seeding catalogs?

**Comment by stevemoser** [comment]
I tried `sudo ./installinstallmacos.py --catalogurl https://swscan.apple.com/content/catalogs/others/index-10.14seed-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz` but no dice. Any other ideas?

**Comment by gregneagle** [comment]
You are assuming that Apple has made it available.

**Comment by gregneagle** [comment]
I'm going to close this, as I am unaware of an available Apple sucatalog that contains the 10.14.5 beta and I have no control over what Apple makes available.
