### ISSUE TITLE
local variable 'dist_path' referenced before assignment

### ISSUE THREAD

**Issue by networkextension** [munki/macadmin-scripts#19]
091-95155.English.dist']' returned non-zero exit status 92
Traceback (most recent call last):
  File "./installinstallmacos.py", line 573, in <module>
    main()
  File "./installinstallmacos.py", line 491, in main
    catalog, args.workdir, ignore_cache=args.ignore_cache)
  File "./installinstallmacos.py", line 396, in os_installer_product_info
    dist_info = parse_dist(dist_path)
UnboundLocalError: local variable 'dist_path' referenced before assignment
st:macadmin-scripts a123$

**Comment by hkatsura** [comment]
except ReplicationError as err:
            print('Could not replicate %s: %s' % (dist_url, err),
                  file=sys.stderr)
            raise err  #  <== maybe we want to raise the exception here?

**Comment by hkatsura** [comment]
CURLE_HTTP2_STREAM (92) : Stream error in the HTTP/2 framing layer.

anyways, you shouldn't have any issues accessing 091-95155.English.dist. does the curl command fail as well trying to access it?

$ curl --head https://swdist.apple.com/content/downloads/12/40/091-95155/piv8296jbzadg8qb5m3gatbllz60d2flsw/091-95155.English.dist
HTTP/2 200
...

**Comment by gregneagle** [comment]
"local variable 'dist_path' referenced before assignment" is addressed by the above commit, but that of course won't address the larger issue, which is that '091-95155.English.dist' failed to replicate. Hopefully that's just a transient local error.
