### ISSUE TITLE
Failing to create sparse image...

### ISSUE THREAD

**Issue by GermanGorbachov** [munki/macadmin-scripts#23]
Script didn't work several times with the following output: 

Making empty sparseimage...
installer: Package name is macOS Mojave
installer: Installing at base path /private/tmp/dmg.T0Ygmn
2019-08-11 07:51:41.692 installer[3344:303436] Package /Volumes/LIB_[1Tb]/OS_X_Archive/content/downloads/16/00/041-94412/t6w6bldyviccosh24jj36g9dy7t7jly9sy/InstallESDDmg.pkg uses a deprecated pre-10.2 format (or uses a newer format but is invalid).
installer: The install failed (The Installer could not install the software because there was no software found to install.)
Command '[u'/usr/sbin/installer', u'-pkg', u'/Volumes/LIB_[1Tb]/OS_X_Archive/content/downloads/16/00/041-94412/t6w6bldyviccosh24jj36g9dy7t7jly9sy/041-94412.English.dist', u'-target', '/private/tmp/dmg.T0Ygmn']' returned non-zero exit status 1
Product installation failed.

___________________________________________________________________
Corresponding chunk of '/var/log/install.log' : 

Aug 11 07:51:41 german-MacPro51 installer[3344]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Aug 11 07:51:41 german-MacPro51 installer[3344]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/LIB_%5B1Tb%5D/OS_X_Archive/content/downloads/16/00/041-94412/t6w6bldyviccosh24jj36g9dy7t7jly9sy/InstallAssistantAuto.pkg
Aug 11 07:51:41 german-MacPro51 installer[3344]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/LIB_%5B1Tb%5D/OS_X_Archive/content/downloads/16/00/041-94412/t6w6bldyviccosh24jj36g9dy7t7jly9sy/InstallESDDmg.pkg
Aug 11 07:51:41 german-MacPro51 installer[3344]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/LIB_%5B1Tb%5D/OS_X_Archive/content/downloads/16/00/041-94412/t6w6bldyviccosh24jj36g9dy7t7jly9sy/RecoveryHDMetaDmg.pkg
Aug 11 07:51:41 german-MacPro51 installer[3344]: Set authorization level to root for session
Aug 11 07:51:41 german-MacPro51 installer[3344]: Administrator authorization granted.
Aug 11 07:51:41 german-MacPro51 installer[3344]: Package file://localhost/Volumes/LIB_%5B1Tb%5D/OS_X_Archive/content/downloads/16/00/041-94412/t6w6bldyviccosh24jj36g9dy7t7jly9sy/InstallESDDmg.pkg not supported by PK
Aug 11 07:51:41 german-MacPro51 installer[3344]: Unable to use PK session due to incompatible packages. Terminating.
Aug 11 07:51:41 german-MacPro51 installer[3344]: Install failed: The Installer could not install the software because there was no software found to install.
___________________________________________________________________

Machine:
![Screen Shot 2019-08-11 at 10 06 54](https://user-images.githubusercontent.com/24270303/62830939-e005df00-bc1f-11e9-91e5-214ea6f763d4.png)
![Screen Shot 2019-08-11 at 10 07 18](https://user-images.githubusercontent.com/24270303/62830941-e300cf80-bc1f-11e9-920f-6e410cf4c152.png)

So, what might be the cause?

**Comment by gregneagle** [comment]
`rm  /Volumes/LIB_[1Tb]/OS_X_Archive/content/downloads/16/00/041-94412/t6w6bldyviccosh24jj36g9dy7t7jly9sy/InstallESDDmg.pkg` and run the script again. That file is corrupted or incomplete.

**Comment by GermanGorbachov** [comment]
I tried deleting that file and downloading it again (by restarting the
script) and all three sources dropped the connection somewhere after one
gigabyte... Guess there might be too much load and I should try again later.
Thank you for sharing the script. You did a great job!
