### ISSUE TITLE
Making empty sparseimage... installer: Error - ERROR_2062F74259

### ISSUE THREAD

**Issue by master-vodawagner** [munki/macadmin-scripts#26]
I get the following error no matter which OS I elect to download on the latest pull of installmacos.py

Making empty sparseimage...
installer: Error - ERROR_2062F74259
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/12/40/091-95155/piv8296jbzadg8qb5m3gatbllz60d2flsw/091-95155.English.dist', u'-target', '/private/tmp/dmg.Dev2AM']' returned non-zero exit status 1
Product installation failed.

I've deleted the contents folder numerous times and tried different WIFI networks to download the files

**Comment by master-vodawagner** [comment]
Incompatible Macbook, just saw your text on the homescreen

**Comment by edgarliu415** [comment]
I'm having the same problem. I see the file Install_macOS_10.15.5-19F101.sparseimage file was created. The file size is 8.26 GB. The download process couldn't finish creating a dmg file, but I get the same error message master-vodwawagner posted. I'm using MacBook air 2018 model, which is a compatible model. I'm not sure what's wrong with the download.
