### ISSUE TITLE
Product installation failed installer: Error - ERROR_2062F74259

### ISSUE THREAD

**Issue by fralau** [munki/macadmin-scripts#28]
I get the following error:

installer: Error - ERROR_2062F74259

```
** Resuming transfer from byte position 2865969
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Downloading http://swcdn.apple.com/content/downloads/12/40/091-95155/piv8296jbzadg8qb5m3gatbllz60d2flsw/InstallESDDmg.pkg...
** Resuming transfer from byte position 4721872697
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Downloading https://swdist.apple.com/content/downloads/12/40/091-95155/piv8296jbzadg8qb5m3gatbllz60d2flsw/InstallESDDmg.pkm...
Downloading http://swcdn.apple.com/content/downloads/12/40/091-95155/piv8296jbzadg8qb5m3gatbllz60d2flsw/BaseSystem.chunklist...
** Resuming transfer from byte position 1984
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Downloading http://swcdn.apple.com/content/downloads/12/40/091-95155/piv8296jbzadg8qb5m3gatbllz60d2flsw/OSInstall.mpkg...
** Resuming transfer from byte position 673751
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Making empty sparseimage...
installer: Error - ERROR_2062F74259
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/12/40/091-95155/piv8296jbzadg8qb5m3gatbllz60d2flsw/091-95155.English.dist', u'-target', '/private/tmp/dmg.pZsNLZ']' returned non-zero exit status 1
Product installation failed.
```

I deleted the `content` directory and restarted, but it failed again. I am trying to get a version of High Sierra for a bricked machine, and it seems that Apple are making it difficult...

**Comment by fralau** [comment]
Note that I found a workaround by using the High Sierra patcher (http://dosdude1.com/highsierra/). Regardless, I believe that having a python utility is a great idea.

**Comment by twocanoes** [comment]
I believe something changed on apple's servers. If you remove the "-z" option from curl, resumes work. I saw the same errors when i cancelled and tried to resume. It leaves incomplete files. Removing the -z option resolve it and allowed it to continue.

**Comment by manicslothpdx** [comment]
Are you using a compatible Mac? This issue is mentioned in the notes on the main page. I just tried this on a compatible Mac and it still works. The number after "ERROR_" may change but it's still the same issue.

**Comment by gregneagle** [comment]
yes. the error would indicate that whatever version of High Sierra you are downloading is not compatible with the hardware you are downloading it on. 

https://github.com/munki/macadmin-scripts#installinstallmacospy

> If you attempt to install an incompatible version of macOS, you'll see an error similar to the following:

```
Making empty sparseimage...
installer: Error - ERROR_B14B14D9B7
Command '['/usr/sbin/installer', '-pkg', './content/downloads/07/20/091-95774/awldiototubemmsbocipx0ic9lj2kcu0pt/091-95774.English.dist', '-target', '/private/tmp/dmg.Hf0PHy']' returned non-zero exit status 1
Product installation failed.
```
> Use a compatible Mac or select a different build compatible with your current hardware and try again. You may also have success running the script in a VM; the InstallationCheck script in versions of the macOS installer to date skips the checks (and returns success) when run on a VM.
```
