### ISSUE TITLE
Upgrade MacOS behaviour

### ISSUE THREAD

**Issue by l4zaro** [munki/macadmin-scripts#30]
Hi,
I'm looking for a script that will upgrade a MacOS 10.13 to 10.14 through ssh.

Does "installinstallmacos.py" script allows me to do so?

According to the Documentation sounds like it will be a clean installation. (which I'm afraid of).
"The tool assembles "Install macOS" applications by downloading the packages from Apple's softwareupdate servers and then installing them into a new empty disk image."

I currently don't have a MacOS machine to run the script and check the "--help" for clarification.
Could you confirm if I can do an "only-upgrade" without losing my current files?

Thanks in advance,

**Comment by FaffeF** [comment]
`softwareupdate -ia --verbose`

**Comment by l4zaro** [comment]
Hi @FaffeF thanks for your answer. Unfortunately as far as I'm aware that only updates to the latest version of the MacOS I'm in. (eg: from 10.13.1 to 10.13.6).

My goal is to upgrade from 10.13.X to 10.14.X

**Comment by FaffeF** [comment]
Yeah, sorry. Should be able to next time though, using `--fetch-full-installer` that's new to Catalina.

**Comment by l4zaro** [comment]
You can close the issue, I could create the .dmg mount and install from there. Works like a charm, thanks a lot
