### ISSUE TITLE
Curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by s0q** [munki/macadmin-scripts#31]
Trying to run it and it's failing, return non-zero exit status 56. 

Thats any version of macos.

**Comment by gregneagle** [comment]
There's really not enough info there to even begin to guess anything other than you are experiencing some sort of network/internet communications issue.

**Comment by s0q** [comment]
Ah I'm sorry, we did some extended troubleshooting and it is the network.
