### ISSUE TITLE
hdutil: create failed - Resource busy

### ISSUE THREAD

**Issue by gsprague** [munki/macadmin-scripts#36]
installmacosinstall.py is giving the following error:

Product downloaded and installed to /Users/<username>/Install_macOS_10.15.1-19B88.sparseimage
Making read-only compressed disk image containing Install macOS Catalina.app...
...............................................................................................................................
hdiutil: create failed - Resource busy
Command '[u'/usr/bin/hdiutil', u'create', u'-fs', u'HFS+', u'-srcfolder', u'/private/tmp/dmg.Td0UZK/Applications/Install macOS Catalina.app', u'./Install_macOS_10.15.1-19B88.dmg']' returned non-zero exit status 1

**Comment by gregneagle** [comment]
Sounds like a local issue -- perhaps AV software poking at the disk image as it is being created? I don't know if it possible to get more logging info from hdiutil...

**Comment by gsprague** [comment]
@gregneagle Yep, CrowdStrike was causing this issue. All set now. Thanks!
