### ISSUE TITLE
Request - Automated mode

### ISSUE THREAD

**Issue by isaacatmann** [munki/macadmin-scripts#37]
Hi - We love this workflow, some of us were discussing how to make it even more friendly by adding in a variable that does the following:

Downloads the latest version of the macOS installer and puts it in /Applications

This would allow for easy additions to and MDM workflow to automatically put the latest full installer on a device somewhere we expect it without having to package and re-push.

**Comment by gregneagle** [comment]
I don't really have a need for that.

Graham Pugh has a fork here: https://github.com/grahampugh/macadmin-scripts that might be more like what you want.

**Comment by grahampugh** [comment]
@isaacatmann In addition to https://github.com/grahampugh/macadmin-scripts,
you might find that https://github.com/grahampugh/erase-install, which is a
wrapper on top of my fork, has all the flags you need. For example:

To download the latest version of the macOS installer and puts it in
/Applications, just run
sudo ./erase-install.sh --move

Cheers
Graham
