### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by tgeorgiop** [munki/macadmin-scripts#39]
Hello, I have mac os catalina and I want to download high sierra from installinstallmacos.py. When I run it and after choosing the high sierra, it downloads some files and after that it shows 

Making empty sparseimage...
installer: Error - ERROR_2062F74259
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/06/50/041-91758-A_M8T44LH2AW/b5r4og05fhbgatve4agwy4kgkzv07mdid9/041-91758.English.dist', u'-target', '/private/tmp/dmg.sb5uza']' returned non-zero exit status 1
Product installation failed.

Could you please help me?

**Comment by kylejericson** [comment]
I have the same issue please fix.

**Comment by gregneagle** [comment]
I won’t be fixing this. “Fixing” thIs would require modification of the distribution file; doing so in an automated fashion would require making assumptions about the distribution file that Apple could break at any time.

**Comment by flammable** [comment]
I know it might be a catch-22, but if you can get a macOS 10.13 VM up and running (or gain access to a physical machine already running 10.13), installinstallmacos.py successfully builds a 10.13.6 installer dmg.

In my case, I had an old 10.13.6 AutoDMG image that I had built in 2018. I used vfuse to convert that to a VM, then ran installinstallmacos.py to download the installers for builds 17G2208 and 17G66.

**Comment by gregneagle** [comment]
I can definitely see the use case for being able to use installinstallmacos.py to download older macOS installers, but it's not a need I have. Making it work would require a fair amount of effort, and Apple could easily break it at any time -- it would require programmatically changing the distribution file for the installer to remove or alter the OS version check. 
This is entirely doable, and I encourage anyone that is interested in this to dig in and do it. But it's not work I need or plan to do, and it's certainly not something I want to support going forward.
