### ISSUE TITLE
Can not fetch the lastest catalina beta

### ISSUE THREAD

**Issue by ShineUnM** [munki/macadmin-scripts#44]
My mbp 2019 has updated to 10.15.4 beta 19E250c using system update
When I use this script with SeedCatalog to build the lastest beta dmg
It only fetch 10.15.4 19E242d version
 #    ProductID    Version    Build   Post Date  Title
 1    061-77704    10.15.4  19E242d  2020-02-26  macOS Catalina Beta
 2    041-91758    10.13.6    17G66  2019-10-19  macOS High Sierra
 3    041-88800    10.14.4  18E2034  2019-10-23  macOS Mojave
 4    061-26589    10.14.6   18G103  2019-10-14  macOS Mojave
 5    061-44387    10.15.3    19D76  2020-01-28  macOS Catalina
 6    041-90855    10.13.5   17F66a  2019-10-23  Install macOS High Sierra Beta
 7    061-26578    10.14.5  18F2059  2019-10-14  macOS Mojave
 8    061-44345    10.15.2   19C39d  2019-11-15  macOS Catalina Beta

Maybe Apple uses a private sucatalog?

**Comment by gregneagle** [comment]
You are making the assumption that Apple makes available a full installer for each beta. We’ve seen that is not the case.
