### ISSUE TITLE
Could not find a default catalog url for this OS version.

### ISSUE THREAD

**Issue by Setaran** [munki/macadmin-scripts#45]
Hello
I have downloaded the 22 MB installer of Mac OS High Sierra on my Sierra VM.
And I tried this command:
` sudo ./installinstallmacos.py `
And I got this error:
`Could not find a default catalog url for this OS version.`

Is it because the VM is not capable of running High Sierra? Is that why I'm getting this error?
How can I achieve a working full 4.5+ GB installer of High Sierra which I'm gonna use as a VM and also install on my Macbook Pro Late 2011?

Thanks very much :)

**Comment by gregneagle** [comment]
You are getting that error because the script does not support running under 10.12.

You might be able to get what you want by explicitly providing a catalogurl:

```
sudo ./installinstallmacos.py --catalogurl https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
```

**Comment by Setaran** [comment]
Thanks very much, your link worked!

But I would like to mention that before asking this question, I read the docs folder, and I had tried this link:

`--catalogurl Software Update catalog URL used by the tool. Defaults to https://swscan.apple.com/content/catalogs/others/index-10.13seed-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog`

I also tried downloading the catalog file and trying a local path to the file but in both cases I got this error:

`Could not replicate https://swscan.apple.com/content/catalogs/others/index-10.13seed-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog5: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'./content/catalogs/others/index-10.13seed-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog5', 'https://swscan.apple.com/content/catalogs/others/index-10.13seed-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog5']' returned non-zero exit status 22`

But as I've said, your link is different than the one in the docs and it works perfectly :)

**Comment by Setaran** [comment]
Oh I just realized, `sudo ./installinstallmacos.py --seedprogram *` also works, and my MBP running El Capitan has also listed Catalina, which my MBP is not supported by it.

**Comment by gregneagle** [comment]
It lists what is in the su catalog -- it has zero idea what is compatible with the hardware you are running.

Glad you got it working; updated the docs. Pretty sure all the 10.13seed catalogs are long gone by now.
