### ISSUE TITLE
Error on 10.15.4

### ISSUE THREAD

**Issue by jeolsen** [munki/macadmin-scripts#46]
Seeing this when i try to download Catalina 10.15.4 from 10.15.3 or 4:

installer: Package name is macOS Catalina
installer: Installing at base path /private/tmp/dmg.QkvqY1
installer: The install was successful.
*********************************************************
*** Working around a very dumb Apple bug in a package ***
*** postinstall script that fails to correctly target ***
*** the Install macOS.app when installed to a volume  ***
*** other than the current boot volume.               ***
***       Please file feedback with Apple!            ***
*********************************************************
ditto: /private/tmp/dmg.QkvqY1/Applications/Install macOS Catalina.app/Contents/SharedSupport/BaseSystem.dmg: No space left on device
Traceback (most recent call last):
  File ".../installmacos.py", line 596, in <module>
    main()
  File ".../installmacos.py", line 563, in main
    mountpoint)
  File ".../installmacos.py", line 232, in install_product
    os.path.join(target_vol, 'Applications')]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/usr/bin/ditto', u'/private/tmp/dmg.QkvqY1Applications', u'/private/tmp/dmg.QkvqY1/Applications']' returned non-zero exit status 1

**Comment by hkatsura** [comment]
i think we need to increase the sparse dmg size. 8g is not big enough. i changed mine to 16g for now and it's working for me.

`    cmd = ['/usr/bin/hdiutil', 'create', '-size', '8g', '-fs', 'HFS+',`

**Comment by Cpuroast** [comment]
I just tried with 9g, that worked fine too.

**Comment by jeolsen** [comment]
That did the trick, 16G worked.  Thank you

**Comment by flammable** [comment]
This issue has been resolved with @aysiu's commit. If you're still seeing this error, update!

**Comment by macguy-ag** [comment]
Seeing this error running on Catalina 10.15.5 trying to download 10.15.5. I changed my sparse dmg size to 16GB and it still fails.

`Making empty sparseimage...
installer: Package name is macOS Catalina
installer: Installing at base path /private/tmp/dmg.wgl4HX
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “InstallESDDmg.pkg”.)
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/22/25/061-70033-A_0AY28AEJF9/am7836x4645ittkll95lsmfk166h9yeivs/061-70033.English.dist', u'-target', '/private/tmp/dmg.wgl4HX']' returned non-zero exit status 1
Product installation failed.`

**Comment by flammable** [comment]
It's probably not the same issue, then. You should open a new GitHub issue.

**Comment by gregneagle** [comment]
Since the error message doesn't reference anything about running out of space it's almost certainly a completely different issue. Have you looked in /var/log/install.log for clues?

**Comment by chriszanf** [comment]
@macguy-ag Encoutnered this issue on 10.15.5 and found in /var/log/install.log the following:

`2020-06-15 12:11:32+01 HOSTNAME installer[66319]: PFPackage::packageWithURL - can't instantiate package: /Users/USERNAME/_IMAGES/./content/downloads/49/02/001-12336-A_QLFL0RTBKY/g7p7womx20182etq6bvffbwe4a41grcxod/001-12336.English.dist`

Found related info that suggested that removing `hdiutil attach **-nobrowse**`

I removed '-nobrowse' from line 171 and that now works:

`cmd = ['/usr/bin/hdiutil', 'attach', dmgpath,
           '-mountRandom', '/tmp', '-plist',
           '-owners', 'on']'
