### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by js-abc007** [munki/macadmin-scripts#50]
Traceback (most recent call last):
  File "installinstallmacos.py", line 599, in <module>
    main()
  File "installinstallmacos.py", line 468, in main
    'are %s.' % ', '.join(get_seeding_programs()))
  File "installinstallmacos.py", line 117, in get_seeding_programs
    seed_catalogs = read_plist(SEED_CATALOGS_PLIST)
  File "installinstallmacos.py", line 77, in read_plist
    with open(filepath, "rb") as fileobj:
IOError: [Errno 2] No such file or directory: u'/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/SeedCatalogs.plist'

**Comment by gregneagle** [comment]
What version of macOS are you running? That file exists on all the versions I've tested to date.

If doesn't exist on your macOS install, I can get rid of the error, but you won't know the available seeding programs.

**Comment by gregneagle** [comment]
I've pushed a change which will catch the IOError, but won't address the underlying issue, which is the absence of /System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/SeedCatalogs.plist on your machine.
