### ISSUE TITLE
Hack default catalog_url to fix "Could not find a default catalog url" for macos 10.11

### ISSUE THREAD

**Issue by dukechem** [munki/macadmin-scripts#52]
``` terminal
bash-4.4$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G22010
bash-4.4$ ./installinstallmacos.py 
Could not find a default catalog url for this OS version.
```
A hack to fix this by using the "something" url from [fetch-macOS.py](https://github.com/kholia/OSX-KVM/blob/master/fetch-macOS.py) is at this gist:
[https://gist.github.com/dukechem/f8f535d279b3d496444abaeb2b11e3e4](https://gist.github.com/dukechem/f8f535d279b3d496444abaeb2b11e3e4)

**Comment by gregneagle** [comment]
Just use the —catalogurl option.
