### ISSUE TITLE
Crash when setting extended attribute

### ISSUE THREAD

**Issue by mbesemann** [munki/macadmin-scripts#54]
Ran into the issue below when attempting to download the macOS 11 beta.  Download completes, but there's a crash when it attempts to set extended attributes.  I installed xattr from pip beforehand.

```
Making empty sparseimage...
installer: Package name is macOS Beta
installer: Installing at base path /private/tmp/dmg.bePlFP
installer: The install was successful.
Adding seeding program DeveloperSeed extended attribute to app
Traceback (most recent call last):
  File "installinstallmacos.py", line 614, in <module>
    main()
  File "installinstallmacos.py", line 593, in main
    xattr.setxattr(installer_app, 'SeedProgram', seeding_program)
  File "/usr/local/lib/python3.7/site-packages/xattr/__init__.py", line 184, in setxattr
    return xattr(f).set(attr, value, options=options)
  File "/usr/local/lib/python3.7/site-packages/xattr/__init__.py", line 78, in set
    return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
  File "/usr/local/lib/python3.7/site-packages/xattr/__init__.py", line 60, in _call
    return name_func(self.value, *args)
  File "/usr/local/lib/python3.7/site-packages/xattr/lib.py", line 77, in _setxattr
    _check_bytes(value)
  File "/usr/local/lib/python3.7/site-packages/xattr/lib.py", line 25, in _check_bytes
    "Value must be bytes, %s was passed." % type(val).__name__
TypeError: Value must be bytes, str was passed.
```

**Comment by gregneagle** [comment]
Sounds like you are not using Apple’s provided Python, then (since you are installing xattr). 

Does it work as expected with Apple’s Python (/usr/bin/Python)?

**Comment by mbesemann** [comment]
@gregneagle ah yes my mistake, I'm so used to using python 3 for everything :) - works fine with python 2.

**Comment by gregneagle** [comment]
I’d accept a PR that made it work with Python 3 as well, but it’s not a priority for me to work on.

**Comment by jazaval** [comment]
@gregneagle this might be more of a priority now that Apple isn't shipping their own python anymore - should I open a new issue?

**Comment by gregneagle** [comment]
Better would be a PR. Otherwise I’ll work on it when I need it, which might not correspond with when you need it…

**Comment by gregneagle** [comment]
Addressed here: https://github.com/munki/macadmin-scripts/commit/a8a6f150c8153fa16f7790b115d56015d0dc13d4
