### ISSUE TITLE
Issue when trying to download MacOS big sure

### ISSUE THREAD

**Issue by 0-Proxy-0** [munki/macadmin-scripts#56]
`Making empty sparseimage...
installer: Package name is macOS Beta
installer: Installing at base path /private/tmp/dmg.x3jwRS
installer: The install was successful.
Adding seeding program DeveloperSeed extended attribute to app
Product downloaded and installed to /Users/davide/Downloads/macadmin-scripts-main/Install_macOS_10.16-20A4299v.sparseimage
Making read-only compressed disk image containing Install macOS Beta.app...
........................................................................
hdiutil: create failed - errore interno
Command '[u'/usr/bin/hdiutil', u'create', u'-fs', u'HFS+', u'-srcfolder', u'/private/tmp/dmg.x3jwRS/Applications/Install macOS Beta.app', u'./Install_macOS_10.16-20A4299v.dmg']' returned non-zero exit status 1`

**Comment by gregneagle** [comment]
Please read the README and focus on the Catalina note.

**Comment by 0-Proxy-0** [comment]
I can't solve the issue moving script folder to /Users/Shared
