### ISSUE TITLE
Not grabbing full image for Big Sur beta 2

### ISSUE THREAD

**Issue by mbesemann** [munki/macadmin-scripts#59]
I used this script successfully for beta 1, however now when I attempt to download beta 2 it's only getting a 155 MB .dmg.  Opening the installer shows a message saying there's important content missing that can't be downloaded:

![Screen Shot 2020-07-08 at 2 23 16 PM](https://user-images.githubusercontent.com/42157326/86956107-91f6a580-c126-11ea-9406-8dbb10947f31.png)

Is it perhaps grabbing the "online" version instead of the full version of the image?

**Comment by gregneagle** [comment]
Worked OK for me yesterday to get Beta 2 using `--seed CustomerSeed`...

**Comment by mbesemann** [comment]
> Worked OK for me yesterday to get Beta 2 using `--seed CustomerSeed`...

interesting, I was using DeveloperSeed but it seems the end result is the same for both.  Before this, I accidentally downloaded the latest Catalina Beta, could it have left some files behind that are interfering with the process?  This is the output of my run:

https://hastebin.com/xoxicuzuvo.cs

![Screen Shot 2020-07-08 at 2 29 25 PM](https://user-images.githubusercontent.com/42157326/86956659-6f18c100-c127-11ea-95af-a1e27b7139bf.png)

**Comment by gregneagle** [comment]
So this can be closed?

**Comment by mbesemann** [comment]
@gregneagle sure, although I still wonder how this issue cropped up in the first place - shouldn't the script handle this sort of scenario?

**Comment by gregneagle** [comment]
Maybe? If you can document a way to reproduce your problem, please create a new issue. But do remember I'm sharing this with no guarantee it works at all. "I found this useful, I hope you do, too!" Unlike the vendor of a commercial product, as long as it works for me there's not a ton of incentive for me to spend too much time trying hard to reproduce issues that I'm not seeing.

If you can post an issue that shows simply and consistently how to reproduce a problem, the odds are higher I'll look at it and fix it. Even better if you have a fix!
