### ISSUE TITLE
problem building the installer package

### ISSUE THREAD

**Issue by featherly** [munki/macadmin-scripts#60]
running on an 11.0 beta 2 machine as root after the parts of Big Sur beta 3 download the package build fails with:

Making empty sparseimage...
installer: Package name is macOS Big Sur Beta
installer: Installing at base path /private/tmp/dmg.QofwOG
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “InstallAssistant.pkg”.)
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/34/37/001-26097-A_OYW4Z0U99Z/gdas3ubse9fasb0217grmmyplfd6o7mqfp/001-26097.English.dist', u'-target', '/private/tmp/dmg.QofwOG']' returned non-zero exit status 1
Product installation failed.

**Comment by gregneagle** [comment]
I don't plan to run this on Big Sur myself any time soon, so this is likely to not be fixed (if possible) by me any time soon. If someone else wants to take a crack at it, please be my guest.

It does work fine to download Big Sur betas when run on Catalina.

**Comment by trodemaster** [comment]
I'm also seeing this issue running the script on macOS 10.15.6. Looking at the install.log I found some permissions denied errors. Moving my working directory from an external disk to a folder in my home directory the script is now working!

**Comment by gregneagle** [comment]
https://github.com/munki/macadmin-scripts/blob/main/README.md#important-note-for-catalina
