### ISSUE TITLE
Could not create a preboot volume for APFS install

### ISSUE THREAD

**Issue by IbrahimFadel** [munki/macadmin-scripts#61]
Hello,

I'm trying to install MacOS Catalina 10.15.4
I ran `installinstallmacos.py` and created the `Install_macOS_10.15.4-19E2269.dmg` file
When i open it and run the installer, it gives me an error: *Could not create a preboot volume for APFS install*
How can I fix this?

**Comment by gregneagle** [comment]
I suspect that's a question for _Apple_.
