### ISSUE TITLE
Option to download macOS beta builds like Big Sur

### ISSUE THREAD

**Issue by welby12** [munki/macadmin-scripts#62]
Would be nice to be able to download Big Sur betas using this script. 

They just released Beta 4 today, and unfortunately in `System Preferences -> Software Update`, it doesn't state which build I am downloading. I have to download a 12 GB file in hope that it's the new one. 

I noticed that in `installinstallmacos.py` it reads:
`Valid seeding programs are: PublicSeed, CustomerSeed, DeveloperSeed`

Does this have anything to do with that capability? 

<img width="1051" alt="big-sur-1" src="https://user-images.githubusercontent.com/13987200/89356026-a1a7d200-d671-11ea-8fa4-98367fe48bf6.png">
<img width="780" alt="big-sur-2" src="https://user-images.githubusercontent.com/13987200/89356036-a4a2c280-d671-11ea-95c5-696353d4c45c.png">

**Comment by gregneagle** [comment]
Why don't you try one and find out? Looks like you are using someone else fork, though (?Graham Pugh's?), as my script does not output like that.

Yes, you can get Big Sur betas.
