### ISSUE TITLE
High Sierra Build 17G2307

### ISSUE THREAD

**Issue by hmalek-iknow** [munki/macadmin-scripts#7]
Thanks a lot for your work. I have an issue that the 2018 MacBook Pro I have has been updated to the Supplemental update 2 and now macOS is 10.13.6 Build 17G2307 and I can't find that specific build when I run your script. your help is much appreciated. 

Best,
Hazem

**Comment by gregneagle** [comment]
You can’t find it because Apple hasn’t made it available as a full installer.
