### ISSUE TITLE
macOS Big Sur Beta 9 (20A5384c)

### ISSUE THREAD

**Issue by TheS0ulReaver** [munki/macadmin-scripts#74]
After executing the installinstallmacos.py, Beta 9 Full installer is not on the list.

<img width="674" alt="Screenshot 2020-10-03 at 13 15 33" src="https://user-images.githubusercontent.com/72302752/94990355-a73f6c80-057b-11eb-9595-c3ac7aa524c1.png">

**Comment by gregneagle** [comment]
No, it not, because it’s not in the standard software update catalog. Use one of the seed catalogs.
