### ISSUE TITLE
Big Sur: Error

### ISSUE THREAD

**Issue by MichelRahme** [munki/macadmin-scripts#80]
## Description

`Could not replicate http://swcdn.apple.com/content/downloads/50/49/001-79699-A_93OMDU5KFG/dkjnjkq9eax1n2wpf8rik5agns2z43ikqu/InstallAssistant.pkg: Command '[u'/usr/bin/curl', u'-fL', u'--create-dirs', u'-o', u'./content/downloads/50/49/001-79699-A_93OMDU5KFG/dkjnjkq9eax1n2wpf8rik5agns2z43ikqu/InstallAssistant.pkg', u'--compressed', 'http://swcdn.apple.com/content/downloads/50/49/001-79699-A_93OMDU5KFG/dkjnjkq9eax1n2wpf8rik5agns2z43ikqu/InstallAssistant.pkg']' returned non-zero exit status 22`

## Command

`sudo ./installinstallmacos.py --seedprogram CustomerSeed --ignore-cache`

**Comment by gregneagle** [comment]
That's an upstream error with Apple or its CDN. Try again later.

I'd also avoid the CustomerSeed (or any Seed catalog) if your goal is to obtain a "release" installer. If you use the seed catalogs, any client you install with an installer retrieved that way will be enrolled in the seed.
