### ISSUE TITLE
Installer failed on Macbook Pro Touchbar

### ISSUE THREAD

**Issue by DiMilan** [munki/macadmin-scripts#83]
I've tried to run the script on my Mabook Pro 14,2.

I get as far as teh selection screen. After the selection it starts downloading but then it gives an error on the installer. 

I just want the full installer to create an USB bootable installation drive.

```
Making empty sparseimage...
installer: Package name is macOS Big Sur
installer: Installing at base path /private/tmp/dmg.9iJiU1
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “InstallAssistant.pkg”.)
Command '[u'/usr/sbin/installer', u'-pkg', u'./content/downloads/00/55/001-86606-A_9SF1TL01U7/5duug9lar1gypwunjfl96dza0upa854qgg/001-86606.English.dist', u'-target', '/private/tmp/dmg.9iJiU1']' returned non-zero exit status 1
Product installation failed.
```

Also tried on a Macbook 12" Retina 9,1 and there I get this error:

```
users-MacBook:macadmin-scripts-main user$ sudo ./installinstallmacos.py
Password:

installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : MacBook9,1

Board ID         : Mac-9AE82516C7C6B903
OS Version       : 10.11.6
Build ID         : 15G31

Could not find a default catalog url for this OS version.
```

**Comment by grahampugh** [comment]
@DiMilan two things:
1. It looks like you are using my fork of `installinstallmacos.py` , so consider creating issues at https://github.com/grahampugh/macadmin-scripts rather than here.
2. My fork won't find a catalog if you run it on a computer as old as OS X 10.11.6. Try using a newer computer, otherwise you'll have to supply an older catalog.
3. I'm interested to know what OS you rhave on the MacBook Pro 14,2?

**Comment by DiMilan** [comment]
1. Ok thanks I will!
2. makes sense
3. Big Sur 11.1

**Comment by DifferentComputers** [comment]
"otherwise you'll have to supply an older catalog."

I'm trying to update 10.11.6 on a machine that theoretically can run Catalina. Where can I find the URL of a catalog that will work for this?
