### ISSUE TITLE
[Feature request] Add aria2 support

### ISSUE THREAD

**Issue by 1alessandro1** [munki/macadmin-scripts#89]
Hi @gregneagle, sorry for posting it as an issue, 

Your tool is very useful to download macOS installers easily using `python` and `curl` which are both shipped by default in macOS.

However, when the connection is weak or servers are overloaded, the download may fail and `curl` isn't able to recover a partial download.

Here's when [aria2c](https://github.com/aria2/aria2) comes into play, solving this issue for any kind of download you're doing (stream over https, or just plain download of a file)

I suggest to add an option to the `.py` maybe as a flag `--use-aria2c`, to replace curl commands with `aria2c`, with an alert like:

```
This option requires aria2c to be present in your $PATH
```

In order to be able to recover a partial download on unstable circumstances

Let me know your thoughts on this, as `aria2c` is a very useful and reliable tool for me and many of my colleagues.

**Comment by gregneagle** [comment]
I don't really have the time or inclination to learn "aria2c" and figure out how to integrate it with installinstallmacos.py. curl works fine for me.
There's nothing stopping you from forking the tool and adding support for aria2c for your own needs, and possibly creating a Pull Request to merge the feature back into this project.

(I write many of these tools largely for my own needs and am happy to share them in case others find them useful, but I don't necessarily have the time and inclination to add features I don't need or won't use, especially if adding and maintaining them is non-trivial)

**Comment by gregneagle** [comment]
Closing as I will not be adding this myself.
