### ISSUE TITLE
ImportError: No module named xattr

### ISSUE THREAD

**Issue by MustyAslan99** [munki/macadmin-scripts#91]
```
File "installinstallmacos.py", line 44, in <module>
    import xattr
ImportError: No module named xattr
```

When trying to run command from (https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-modern-os) guide.

**Comment by gregneagle** [comment]
Apple's built-in Python includes xattr. If the Python you are using does not, you'll have to install it.

**Comment by gregneagle** [comment]
(I'd imagine replacing `python` with `/usr/bin/python` in that command would fix things)

**Comment by MustyAslan99** [comment]
i tried from linux. guessed it would work without mac. :/

**Comment by gregneagle** [comment]
There is zero support for Linux. Not saying it would be impossible to make it work on Linux, but it's work I don't need to do.

**Comment by MustyAslan99** [comment]
thanks for reply will try to get mac then. if this issue is my side end.
