### ISSUE TITLE
import xattr

### ISSUE THREAD

**Issue by jredfox** [munki/macadmin-scripts#92]
install instruction unclear. I installed python 3.9 with the latest release build. I ran 
```
C:\Users\jredf\Desktop\macadmin-scripts-main\installinstallmacos.py help
```
output
```
Traceback (most recent call last):
  File "C:\Users\jredf\Desktop\macadmin-scripts-main\installinstallmacos.py", line 36, in <module>
    import xattr
ModuleNotFoundError: No module named 'xattr'
```

**Comment by gregneagle** [comment]
This tool is only supported with Apple's default Python and on macOS. If you want to use a different Python, you can, but that's on you to figure out and install all the needed dependencies. (like xattr).

It's definitely not supported on Windows.

**Comment by jredfox** [comment]
you can only run the python on macOs when python is a cross platform language sounds like a bug to me
