### ISSUE TITLE
Don't detect latest Catalina

### ISSUE THREAD

**Issue by Tb3986** [munki/macadmin-scripts#96]
Hello,
thanks for your script but i can't get latest Catalina (11.6). Released yesterday and not yet available. Usually after 15-20 minutes you can get the new one but not this time.
Do i have to wait or macadmin need for an update?

Thank you.

**Comment by gregneagle** [comment]
Apple has not made it available as a full installer yet. It’s not available vis the App Store, nor is an IPSW available.
