### ISSUE TITLE
Error Making read-only compressed disk image containing Install macOS Big Sur.app

### ISSUE THREAD

**Issue by sudyhardy** [munki/macadmin-scripts#97]
installer: Package name is macOS Big Sur
installer: Installing at base path /private/tmp/dmg.q5NMWM
installer: The install was successful.
*********************************************************
*** Working around a very dumb Apple bug in a package ***
*** postinstall script that fails to correctly target ***
*** the Install macOS.app when installed to a volume  ***
*** other than the current boot volume.               ***
***       Please file feedback with Apple!            ***
*********************************************************
Product downloaded and installed to /Users/archardy/macOS-installer/Install_macOS_11.6-20G165.sparseimage
Making read-only compressed disk image containing Install macOS Big Sur.app...
........................................................................
hdiutil: create failed - internal error
Command '[u'/usr/bin/hdiutil', u'create', u'-fs', u'HFS+', u'-srcfolder', u'/private/tmp/dmg.q5NMWM/Applications/Install macOS Big Sur.app', u'./Install_macOS_11.6-20G165.dmg']' returned non-zero exit status 1

**Comment by gregneagle** [comment]
Just tested again here successfully:
```
Making empty sparseimage...
installer: Package name is macOS Big Sur
installer: Installing at base path /private/tmp/dmg.CjZwLq
installer: The install was successful.
*********************************************************
*** Working around a very dumb Apple bug in a package ***
*** postinstall script that fails to correctly target ***
*** the Install macOS.app when installed to a volume  ***
*** other than the current boot volume.               ***
***       Please file feedback with Apple!            ***
*********************************************************
Product downloaded and installed to /Users/Shared/macadmin-scripts/Install_macOS_11.6-20G165.sparseimage
Making read-only compressed disk image containing Install macOS Big Sur.app...
..........................................................................................................................................
created: /Users/Shared/macadmin-scripts/Install_macOS_11.6-20G165.dmg
Disk image created at: ./Install_macOS_11.6-20G165.dmg
```
